@rootUrl = http://localhost:8001/api/v2

@userApi = {{rootUrl}}/front-users

@productAPI = http://localhost:8001/api/v2/products


### sign up
POST {{userApi}}
Content-Type: application/json

{
    "fName":"sam",
  "lName": "smith",
  "email":"sam@smith.com" ,
  "phone":"23456" ,
  "address": "ajdskfhahg",
  "password": "1aAaaa"
}

###

GET {{productAPI}}
Content-Type: application/json
